-- ============================================================
-- PM Scheduler — Development Seed Data
-- ============================================================
-- IMPORTANT: Users in this file must ALSO have Supabase Auth accounts
-- with matching UUIDs. To set this up:
--   1. Go to Supabase Dashboard → Authentication → Users
--   2. Create each user with the email and a temporary password
--   3. Copy the generated UUID from the Auth users list
--   4. Replace the UUIDs below with the actual Auth UUIDs before running
--      this seed, OR run this seed first and then create Auth users
--      with matching UUIDs via the Supabase service role API.
--
-- The easiest approach in development:
--   1. Run this seed file
--   2. Use the Supabase SQL editor to SELECT id, email FROM users
--   3. For each user, go to Auth → Users → Invite User (use same email)
--   4. Then update the users.id to match the Auth UID that was generated
-- ============================================================

-- ============================================================
-- CUSTOMERS (synced from Synergy)
-- ============================================================

INSERT INTO customers (synergy_id, name, account_number, ar_terms, credit_hold, billing_address, synced_at)
VALUES
  ('SYN-001', 'Riverside Medical Center', 'RMC-4421', 'Net 30', FALSE,
   '1200 Medical Plaza Drive, Birmingham, AL 35233', now()),
  ('SYN-002', 'Southgate Office Complex', 'SOC-2817', 'Net 45', FALSE,
   '800 Corporate Parkway, Suite 100, Hoover, AL 35244', now()),
  ('SYN-003', 'Tuscaloosa Public Schools', 'TPS-9034', 'Net 60', FALSE,
   '411 Education Boulevard, Tuscaloosa, AL 35401', now());

-- ============================================================
-- CONTACTS
-- ============================================================

INSERT INTO contacts (customer_id, synergy_id, name, email, phone, is_primary) VALUES
  -- Riverside Medical Center
  ((SELECT id FROM customers WHERE synergy_id = 'SYN-001'), 'SYN-C-001', 'Patricia Holloway', 'p.holloway@riversidemedical.com', '205-555-0142', TRUE),
  ((SELECT id FROM customers WHERE synergy_id = 'SYN-001'), 'SYN-C-002', 'Marcus Webb', 'm.webb@riversidemedical.com', '205-555-0198', FALSE),
  -- Southgate Office Complex
  ((SELECT id FROM customers WHERE synergy_id = 'SYN-002'), 'SYN-C-003', 'Donna Fitch', 'donna.fitch@southgateoffice.com', '205-555-0361', TRUE),
  ((SELECT id FROM customers WHERE synergy_id = 'SYN-002'), 'SYN-C-004', 'Ray Callahan', 'r.callahan@southgateoffice.com', '205-555-0277', FALSE),
  -- Tuscaloosa Public Schools
  ((SELECT id FROM customers WHERE synergy_id = 'SYN-003'), 'SYN-C-005', 'Angela Torres', 'a.torres@tuscaloosaschools.org', '205-555-0589', TRUE),
  ((SELECT id FROM customers WHERE synergy_id = 'SYN-003'), 'SYN-C-006', 'Jerome Hicks', 'j.hicks@tuscaloosaschools.org', '205-555-0614', FALSE);

-- ============================================================
-- PRODUCTS (synced from Synergy)
-- ============================================================

INSERT INTO products (synergy_id, number, description, unit_price, synced_at)
VALUES
  ('PRD-001', 'BATT-36V-AGM', 'AGM Battery 36V for rider scrubbers', 189.00, now()),
  ('PRD-002', 'BRUSH-17-PAD', '17-inch scrub brush pad driver assembly', 62.50, now()),
  ('PRD-003', 'SQUEEGEE-BLADE-KIT', 'Rear squeegee blade replacement kit', 34.00, now()),
  ('PRD-004', 'FILTER-VACTOR-HEPA', 'HEPA filter for vacuum/sweeper combo units', 47.75, now()),
  ('PRD-005', 'LABOR-TECH-STD', 'Standard technician labor (per hour)', 85.00, now());

-- ============================================================
-- USERS
-- ============================================================
-- NOTE: These UUIDs are placeholders. In a real deployment, these must
-- match the UUIDs generated by Supabase Auth. See the header note above.

INSERT INTO users (id, email, name, role, active)
VALUES
  ('00000000-0000-0000-0000-000000000001', 'manager@example.com', 'Sarah Kowalski', 'manager', TRUE),
  ('00000000-0000-0000-0000-000000000002', 'coordinator@example.com', 'Derek Johnson', 'coordinator', TRUE),
  ('00000000-0000-0000-0000-000000000003', 'tech@example.com', 'Mike Tanner', 'technician', TRUE);

-- ============================================================
-- EQUIPMENT
-- ============================================================

INSERT INTO equipment (id, customer_id, default_technician_id, make, model, serial_number, description, location_on_site, active)
VALUES
  ('aaaa0000-0000-0000-0000-000000000001',
   (SELECT id FROM customers WHERE synergy_id = 'SYN-001'),
   '00000000-0000-0000-0000-000000000003',
   'Tennant', 'T7', 'T7-2021-88321',
   'Rider floor scrubber — 28 inch deck',
   'Basement loading dock utility hall',
   TRUE),
  ('aaaa0000-0000-0000-0000-000000000002',
   (SELECT id FROM customers WHERE synergy_id = 'SYN-002'),
   '00000000-0000-0000-0000-000000000003',
   'Nilfisk', 'SC500', 'NIL-SC500-44017',
   'Walk-behind auto scrubber',
   'Main lobby janitorial closet',
   TRUE),
  ('aaaa0000-0000-0000-0000-000000000003',
   (SELECT id FROM customers WHERE synergy_id = 'SYN-003'),
   '00000000-0000-0000-0000-000000000003',
   'Advance', 'Advenger 2800', 'ADV-28-67203',
   'Rider sweeper/scrubber combo for gymnasium floors',
   'Gymnasium equipment bay — Building C',
   TRUE);

-- ============================================================
-- PM SCHEDULES
-- ============================================================

INSERT INTO pm_schedules (id, equipment_id, frequency, billing_type, flat_rate, active)
VALUES
  ('bbbb0000-0000-0000-0000-000000000001',
   (SELECT id FROM equipment WHERE serial_number = 'T7-2021-88321'),
   'monthly', 'flat_rate', 225.00, TRUE),
  ('bbbb0000-0000-0000-0000-000000000002',
   (SELECT id FROM equipment WHERE serial_number = 'NIL-SC500-44017'),
   'quarterly', 'time_and_materials', NULL, TRUE);

-- ============================================================
-- PM TICKETS
-- ============================================================

INSERT INTO pm_tickets (
  id, pm_schedule_id, equipment_id, customer_id,
  assigned_technician_id, created_by_id,
  month, year, status, scheduled_date, completed_date,
  completion_notes, hours_worked, parts_used, billing_amount, billing_exported
)
VALUES
  -- Completed and billed — January
  ('cccc0000-0000-0000-0000-000000000001',
   'bbbb0000-0000-0000-0000-000000000001',
   (SELECT id FROM equipment WHERE serial_number = 'T7-2021-88321'),
   (SELECT id FROM customers WHERE synergy_id = 'SYN-001'),
   '00000000-0000-0000-0000-000000000003',
   '00000000-0000-0000-0000-000000000002',
   1, 2026, 'billed',
   '2026-01-15', '2026-01-15',
   'Replaced squeegee blade, cleaned brush deck, checked battery — all good.',
   1.5,
   '[{"product_id": 3, "quantity": 1, "unit_price": 34.00}]',
   225.00, TRUE),

  -- Completed, not yet billed — February
  ('cccc0000-0000-0000-0000-000000000002',
   'bbbb0000-0000-0000-0000-000000000001',
   (SELECT id FROM equipment WHERE serial_number = 'T7-2021-88321'),
   (SELECT id FROM customers WHERE synergy_id = 'SYN-001'),
   '00000000-0000-0000-0000-000000000003',
   '00000000-0000-0000-0000-000000000002',
   2, 2026, 'completed',
   '2026-02-12', '2026-02-14',
   'Full PM completed. Pad driver showing wear — recommended replacement within 60 days.',
   2.0,
   '[]',
   225.00, FALSE),

  -- In progress — March
  ('cccc0000-0000-0000-0000-000000000003',
   'bbbb0000-0000-0000-0000-000000000001',
   (SELECT id FROM equipment WHERE serial_number = 'T7-2021-88321'),
   (SELECT id FROM customers WHERE synergy_id = 'SYN-001'),
   '00000000-0000-0000-0000-000000000003',
   '00000000-0000-0000-0000-000000000002',
   3, 2026, 'in_progress',
   '2026-03-19', NULL,
   NULL, NULL, '[]', NULL, FALSE),

  -- Unassigned — Q1 quarterly ticket
  ('cccc0000-0000-0000-0000-000000000004',
   'bbbb0000-0000-0000-0000-000000000002',
   (SELECT id FROM equipment WHERE serial_number = 'NIL-SC500-44017'),
   (SELECT id FROM customers WHERE synergy_id = 'SYN-002'),
   NULL,
   '00000000-0000-0000-0000-000000000002',
   1, 2026, 'unassigned',
   '2026-01-28', NULL,
   NULL, NULL, '[]', NULL, FALSE);
